- tools/shannon.py
PID controller: Added K_p, K_i and K_d terms
> PID controller

- fri/server/main.py
- fri/test.py
@pradeeban 
Just passed the 'outdir' argument to API's in main.py and test.py. Moreover, calls in test.py changed.
This PR can be reviewed.
Thank You
> Case 2 solved as mentioned in #52

- fri/README.md
- fri/requirements.txt
- fri/test.py
With one step all the dependencies installed and updating README.md
> With one step all the dependencies installed and updating README.md

- concore.hpp
I tested with many other test cases too.
> Shared Memory v1.0.0

- concore.hpp
As discussed in meeting on 23th June, 2023, implementation of shared memory based on edge name, has been done.
> Implemented multiple shared memory based on edge name

- fri/server/main.py
- makedocker
- makedocker.bat
- makestudy
- mkconcore.py
@pradeeban
- It can be noticed that "chmod +x \*/\*" is added to makestudy and makedocker scripts. It is because when I executed them in the newly installed Ubuntu 20.04, a permission denied error was coming even while executing all methods (even from CLI).
- Moreover, (after makestudy is executed) for any posix system, the interpreter directive (shebang) is not present in the scripts of params and unlock. The same goes for the case of makedocker execution, for any script created the interpreter directive (shebang) is absent. Therefore, I made some changes in [mkconcore.py](https://github.com/Rahuljagwani/concore/blob/main/mkconcore.py). If you remember in Friday's meeting I was getting an error **Exec format error: './build'**, it was because of this issue only. Even though from CLI we …
> Options button features in API updated

- fri/server/main.py
> Octave implemented in FRI

- concore.hpp
- Comments has been added in concore.hpp
- shared memory is based on initial digits of edge has been implemented.
> Shared Memory initial digit on edge approch

- contribute.py
Hi @pradeeban , @markgarnold 
As discussed last week I changed my account name to `concore-bot` and also pushed the optimizations I did this PR.
Account https://github.com/concore-bot
I would like to hear any reviews on this PR (if any)
> Code optimizations

- contribute
- contribute.bat
- contribute.py
A found a issue that PR title and body is not updating as expecting we want , This PR fixes that bug
> Fixed issue of not updating title and body by user

- fri/server/main.py
- library
> Symbolic Link Implementation 

- contribute.py
Hi @pradeeban first please try uploading the `example ` folder present in the concore repo to test this
> Contribute action

- .vscode/settings.json
- concore.hpp
I added more comments, so that any other developer can easily understand my implementation. Also remove some unwanted comments and prints.
> Addition and Removal of Comments

- fri/server/main.py
- fri/test.py
fix #117 , by converting the strings to raw strings wherever required
also test.py is improved now
- i fixed download function test by correctly handling the response, however the download function still cant find the file that needs to be downloaded
- removed deprecated unused import of CGI
> Fixed Warning While Running Flask Server On Non-Windows Platform, improved test.py

- mkconcore.py
fixed #119 ,
tested on macOS & Ubuntu, White Spaces Won't Cause Errors From Now On. 
also fixed a warning because of an invalid escape sequence.
> Fixed Space Issues In The Directory And A path warning while making new study

- mkconcore.py
Revised PR #132 , Without Additional Commits.
Fixed Issue #124 ,
I Replaced all Print Statements with their required level of logging
> (Revised PR #132) Fixing Issue #124 , Implemented Logging for debugging in mkconcore.py

- contribute.py
Fix for Issue #135 :
I have **tested** these changes against the forked concore-studies repository using the correct credentials of the bot account. Everything is working perfectly now. However, the credentials need to be updated to match the **bot account with collaborator access in ControlCore-project/concore-studies**.
> Optimized PR Checking, Branch Handling, And Workflow Timing Attempts, Along With Some Minor Issues Fixed

- concore.py
- concoredocker.py
fix #137 ,
I've made the required changes in concore.py and concoredocker.py
will soon raise a request for concoredocker.java too.
thanks
> Fixing Issue #137 partially for concore.py and concoredocker.py

- concoredocker.hpp
fix issue #136 , I've added code for concoredocker.hpp with the same logic as per concoredocker.py, however it is not tested yet.
> Adding concoredocker.hpp as per concoredocker.py

- fri/DOCKER-README.md
- fri/docker-compose.yml
fixed issue #144 ,
Migrated kong with cassandra to docker with postgres in DOCKER-README.md
> Migrated kong with cassandra to kong with postgres in fri/server

- fri/Dockerfile
> Fixing SSL Certificates errors and Support for ARM Architecture
